apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibctl.secretName" . }}
  labels:
    {{- include "ibctl.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

